// AUTO-GENERATED by scripts/bump-version.mjs — do not edit by hand.
// To change major/minor, edit src/assets/version.json's "version" field;
// the patch is auto-bumped on every `npm run build` / `build:ssr`.
// Imported by:
//   - src/logger/index.ts                          (SSR Logger)
export const RELEASE = 'v0.0.1';
