import { Block, ColumnWidth } from '../types/block.types';
import { BlockDefinition, blockRegistry } from './block-registry';

const newId = (prefix: string): string =>
  `${prefix}_${Math.random().toString(36).slice(2, 10)}`;

const fr = (n: number): ColumnWidth => ({ kind: 'fraction', fr: n });

/**
 * Default definitions for every built-in block. Tenants register additional
 * blocks via `blockRegistry.register(...)` — kept side-effect free here so
 * tree-shaking works for SSR.
 */
export const defaultBlockDefinitions: BlockDefinition<Block>[] = [
  {
    type: 'text',
    label: 'Text',
    icon: 'T',
    category: 'basic',
    description: 'Static or bound text. Supports {{bindings}}.',
    factory: (id) => ({
      id,
      type: 'text',
      position: { x: 10, y: 10 },
      size: { width: 60, height: 8, autoHeight: true },
      text: 'Sample text',
      style: { font: { size: 10 } },
    }),
    propertyGroups: ['position', 'size', 'binding', 'typography', 'background', 'border', 'spacing', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'rich-text',
    label: 'Rich Text',
    icon: 'R',
    category: 'basic',
    factory: (id) => ({
      id,
      type: 'rich-text',
      position: { x: 10, y: 10 },
      size: { width: 80, height: 30, autoHeight: true },
      html: '<p>Rich <b>text</b></p>',
    }),
    propertyGroups: ['position', 'size', 'binding', 'typography', 'background', 'border', 'spacing', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'image',
    label: 'Image',
    icon: 'I',
    category: 'media',
    factory: (id) => ({
      id,
      type: 'image',
      position: { x: 10, y: 10 },
      size: { width: 30, height: 30 },
      source: '',
      fit: 'contain',
    }),
    propertyGroups: ['position', 'size', 'image', 'border', 'visibility'],
    resizable: true,
  },
  {
    type: 'line',
    label: 'Line',
    icon: '—',
    category: 'layout',
    factory: (id) => ({
      id,
      type: 'line',
      position: { x: 10, y: 50 },
      size: { width: 100, height: 0.5 },
      thickness: 0.5,
      color: '#000000',
      orientation: 'horizontal',
    }),
    propertyGroups: ['position', 'size', 'visibility'],
    resizable: true,
  },
  {
    type: 'rectangle',
    label: 'Rectangle',
    icon: '▭',
    category: 'layout',
    factory: (id) => ({
      id,
      type: 'rectangle',
      position: { x: 10, y: 10 },
      size: { width: 60, height: 30 },
      fill: '#f3f4f6',
    }),
    propertyGroups: ['position', 'size', 'background', 'border', 'visibility'],
    resizable: true,
  },
  {
    type: 'divider',
    label: 'Divider',
    icon: '╌',
    category: 'layout',
    factory: (id) => ({
      id,
      type: 'divider',
      position: { x: 10, y: 50 },
      size: { width: 180, height: 1 },
      thickness: 0.5,
      color: '#e5e7eb',
      pattern: 'solid',
    }),
    propertyGroups: ['position', 'size', 'divider', 'visibility'],
    resizable: true,
  },
  {
    type: 'qr-code',
    label: 'QR Code',
    icon: 'Q',
    category: 'media',
    factory: (id) => ({
      id,
      type: 'qr-code',
      position: { x: 10, y: 10 },
      size: { width: 30, height: 30 },
      value: '{{invoice.qrPayload}}',
      ecLevel: 'M',
      margin: 0,
    }),
    propertyGroups: ['position', 'size', 'binding', 'visibility'],
    resizable: true,
  },
  {
    type: 'barcode',
    label: 'Barcode',
    icon: '|||',
    category: 'media',
    factory: (id) => ({
      id,
      type: 'barcode',
      position: { x: 10, y: 10 },
      size: { width: 50, height: 18 },
      value: '{{invoice.number}}',
      symbology: 'code128',
      showText: true,
    }),
    propertyGroups: ['position', 'size', 'barcode', 'visibility'],
    resizable: true,
  },
  {
    type: 'signature',
    label: 'Signature',
    icon: '✎',
    category: 'basic',
    factory: (id) => ({
      id,
      type: 'signature',
      position: { x: 10, y: 200 },
      size: { width: 60, height: 20 },
      label: 'Signature',
    }),
    propertyGroups: ['position', 'size', 'signature', 'typography', 'visibility'],
    resizable: true,
  },
  {
    type: 'page-number',
    label: 'Page Number',
    icon: '#',
    category: 'basic',
    factory: (id) => ({
      id,
      type: 'page-number',
      position: { x: 170, y: 280 },
      size: { width: 30, height: 6 },
      format: 'Page {{page.current}} of {{page.total}}',
      style: { font: { size: 8 }, align: 'right' },
    }),
    propertyGroups: ['position', 'size', 'typography', 'page-number', 'visibility'],
    resizable: true,
  },
  {
    type: 'dynamic-field',
    label: 'Dynamic Field',
    icon: 'ƒ',
    category: 'data',
    factory: (id) => ({
      id,
      type: 'dynamic-field',
      position: { x: 10, y: 10 },
      size: { width: 50, height: 6, autoHeight: true },
      expression: 'invoice.total | currency:BHD',
      style: { font: { size: 10 } },
    }),
    propertyGroups: ['position', 'size', 'typography', 'binding', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'table',
    label: 'Table',
    icon: '⊞',
    category: 'data',
    factory: (id) => ({
      id,
      type: 'table',
      position: { x: 10, y: 80 },
      size: { width: 190, height: 60, autoHeight: true },
      dataSource: 'invoice.items',
      showHeader: true,
      showFooter: true,
      repeatHeader: true,
      pageBreak: true,
      zebra: true,
      zebraColor: '#fafafa',
      rowMinHeight: 7,
      columns: [
        {
          id: newId('col'),
          header: 'Item',
          expression: 'row.name',
          width: fr(4),
          align: 'left',
        },
        {
          id: newId('col'),
          header: 'Qty',
          expression: 'row.qty',
          width: fr(1),
          align: 'right',
          footer: { kind: 'sum', expression: 'row.qty', format: 'number:0' },
        },
        {
          id: newId('col'),
          header: 'Price',
          expression: 'row.price | currency:BHD',
          width: fr(2),
          align: 'right',
        },
        {
          id: newId('col'),
          header: 'Total',
          expression: 'row.qty * row.price | currency:BHD',
          width: fr(2),
          align: 'right',
          footer: { kind: 'sum', expression: 'row.qty * row.price', format: 'currency:BHD' },
        },
      ],
    }),
    propertyGroups: ['position', 'size', 'background', 'border', 'binding', 'table-columns', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'totals',
    label: 'Totals',
    icon: 'Σ',
    category: 'data',
    factory: (id) => ({
      id,
      type: 'totals',
      position: { x: 120, y: 200 },
      size: { width: 80, height: 30, autoHeight: true },
      labelWidth: 35,
      rows: [
        { label: 'Subtotal', expression: 'invoice.subtotal | currency:BHD' },
        { label: 'VAT 10%', expression: 'invoice.tax | currency:BHD' },
        { label: 'Total', expression: 'invoice.total | currency:BHD', bold: true },
      ],
    }),
    propertyGroups: ['position', 'size', 'typography', 'totals-rows', 'border', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'payments',
    label: 'Payments',
    icon: '$',
    category: 'data',
    description: 'Fixed-column table of invoice payments (method, reference, date, amount).',
    factory: (id) => ({
      id,
      type: 'payments',
      position: { x: 10, y: 230 },
      size: { width: 120, height: 24, autoHeight: true },
      dataSource: 'invoicePayments',
      columns: ['method', 'reference', 'date', 'amount'],
      showHeader: true,
      showBorder: true,
      zebra: true,
      zebraColor: '#fafafa',
      rowMinHeight: 7,
      currency: 'BHD',
    }),
    propertyGroups: ['position', 'size', 'typography', 'background', 'border', 'binding', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'repeater',
    label: 'Card List',
    icon: '▦',
    category: 'data',
    description: 'Repeats child blocks once per data-source row — like a table but with free positioning inside each card.',
    factory: (id) => ({
      id,
      type: 'repeater',
      position: { x: 10, y: 80 },
      size: { width: 190, height: 30, autoHeight: true },
      dataSource: 'lines',
      itemHeight: 30,
      itemSpacing: 2,
      pageBreak: true,
      direction: 'vertical',
      items: [
        // One sample child so the user sees something inside the card by
        // default. They'll add real content via toolbox drag while the
        // repeater is selected, or via the property-panel "Add child" menu.
        {
          id: newId('blk'),
          type: 'text',
          position: { x: 2, y: 2 },
          size: { width: 60, height: 6, autoHeight: true },
          text: '{{row.productName}}',
          style: { font: { size: 11, weight: 'bold' } },
        },
      ],
    }),
    propertyGroups: ['position', 'size', 'background', 'border', 'binding', 'visibility'],
    autoHeight: true,
    resizable: true,
  },
  {
    type: 'group-header',
    label: 'Group Header',
    icon: '▣',
    category: 'data',
    factory: (id) => ({
      id,
      type: 'group-header',
      position: { x: 10, y: 10 },
      size: { width: 190, height: 8 },
      groupBy: 'row.category',
      template: '{{group.key}}',
      style: { font: { weight: 'bold' }, background: '#f9fafb', padding: { left: 2, top: 1, bottom: 1, right: 2 } },
    }),
    propertyGroups: ['position', 'size', 'typography', 'background', 'visibility'],
  },
  {
    type: 'group-footer',
    label: 'Group Footer',
    icon: '▤',
    category: 'data',
    factory: (id) => ({
      id,
      type: 'group-footer',
      position: { x: 10, y: 10 },
      size: { width: 190, height: 8 },
      groupBy: 'row.category',
      template: 'Subtotal: {{group.rows | length}} items',
      style: { font: { italic: true }, padding: { left: 2, top: 1, bottom: 1, right: 2 } },
    }),
    propertyGroups: ['position', 'size', 'typography', 'background', 'visibility'],
  },
];

/** Convenience: register all built-ins. Call once at bootstrap. */
export function registerDefaultBlocks(): void {
  for (const def of defaultBlockDefinitions) blockRegistry.register(def);
}
