import { ReportTemplate } from '../core/types/template.types';
import { Block } from '../core/types/block.types';
import { makeTemplateId, makeSectionId, makeBlockId } from '../utils/id.utils';

/**
 * Sample A4 invoice template. Bindings target the real Invo POS invoice shape
 * (flat top-level fields like `branchName`, `customerName`, `lines`, `total`)
 * so the preview renders against actual production data without a mapping
 * layer.
 *
 * Layout: page-header with logo + branch info + INVOICE title, body with
 * customer info + metadata grid + line-items table + totals + QR + signature,
 * page-footer with branch info + page number.
 */
export function sampleInvoiceTemplate(): ReportTemplate {
  const now = new Date().toISOString();

  // Inline SVG logo — kept on the block itself because the real invoice
  // payload has no logo field. Swap to a binding (e.g. `{{branch.logoUrl}}`)
  // once that field exists upstream.
  const logoSvg =
    'data:image/svg+xml;utf8,' +
    encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 40">' +
      '<rect width="80" height="40" rx="4" fill="#1e40af"/>' +
      '<text x="40" y="26" text-anchor="middle" fill="white" font-family="Inter,Arial" font-size="18" font-weight="700">INVO</text>' +
      '</svg>',
    );

  const headerBlocks: Block[] = [
    {
      id: makeBlockId(),
      type: 'image',
      position: { x: 15, y: 8 },
      size: { width: 30, height: 18 },
      source: logoSvg,
      fit: 'contain',
      alt: 'Logo',
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 50, y: 9 },
      size: { width: 90, height: 7 },
      text: '{{branchName}}',
      style: { font: { size: 14, weight: 'bold', color: '#0f172a' } },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 50, y: 16 },
      size: { width: 90, height: 12 },
      text: '{{branchAddress}}\nVAT: {{companyVatNumber}}',
      style: { font: { size: 8, color: '#475569' } },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 150, y: 8 },
      size: { width: 45, height: 9 },
      text: 'INVOICE',
      style: { font: { size: 20, weight: 'bold', color: '#1e40af' }, align: 'right' },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 150, y: 17 },
      size: { width: 45, height: 6 },
      text: 'فاتورة',
      style: { font: { size: 12, color: '#475569' }, align: 'right', direction: 'rtl' },
    },
    {
      id: makeBlockId(),
      type: 'divider',
      position: { x: 15, y: 30 },
      size: { width: 180, height: 0.5 },
      thickness: 0.5,
      color: '#cbd5e1',
      pattern: 'solid',
    },
  ];

  const bodyBlocks: Block[] = [
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 15, y: 5 },
      size: { width: 60, height: 5 },
      text: 'BILL TO',
      style: { font: { size: 8, weight: 'bold', color: '#64748b', letterSpacing: 0.5 } },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 15, y: 10 },
      size: { width: 80, height: 18 },
      text: '{{customerName}}\n{{customerAddress}}\n{{customerPhone}}',
      style: { font: { size: 9, color: '#0f172a' } },
    },
    {
      id: makeBlockId(),
      type: 'rectangle',
      position: { x: 110, y: 5 },
      size: { width: 85, height: 25 },
      fill: '#f8fafc',
      style: { border: { top: { width: 0.5, color: '#e2e8f0', style: 'solid' }, right: { width: 0.5, color: '#e2e8f0', style: 'solid' }, bottom: { width: 0.5, color: '#e2e8f0', style: 'solid' }, left: { width: 0.5, color: '#e2e8f0', style: 'solid' } } },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 113, y: 7 },
      size: { width: 40, height: 5 },
      text: 'Invoice #',
      style: { font: { size: 8, color: '#64748b' } },
    },
    {
      id: makeBlockId(),
      type: 'dynamic-field',
      position: { x: 153, y: 7 },
      size: { width: 40, height: 5 },
      expression: 'invoiceNumber',
      style: { font: { size: 9, weight: 'bold', color: '#0f172a' }, align: 'right' },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 113, y: 13 },
      size: { width: 40, height: 5 },
      text: 'Date',
      style: { font: { size: 8, color: '#64748b' } },
    },
    {
      id: makeBlockId(),
      type: 'dynamic-field',
      position: { x: 153, y: 13 },
      size: { width: 40, height: 5 },
      expression: "invoiceDate | date:'medium'",
      style: { font: { size: 9, color: '#0f172a' }, align: 'right' },
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 113, y: 19 },
      size: { width: 40, height: 5 },
      text: 'Due',
      style: { font: { size: 8, color: '#64748b' } },
    },
    {
      id: makeBlockId(),
      type: 'dynamic-field',
      position: { x: 153, y: 19 },
      size: { width: 40, height: 5 },
      expression: "dueDate | date:'medium'",
      style: { font: { size: 9, color: '#dc2626' }, align: 'right' },
    },
    // Items table — bound to top-level `lines[]`.
    {
      id: makeBlockId(),
      type: 'table',
      position: { x: 15, y: 35 },
      size: { width: 180, height: 80, autoHeight: true },
      dataSource: 'lines',
      showHeader: true,
      showFooter: true,
      repeatHeader: true,
      pageBreak: true,
      zebra: true,
      zebraColor: '#f8fafc',
      rowMinHeight: 12,
      columns: [
        {
          id: 'col_idx',
          header: '#',
          expression: 'rowIndex + 1',
          width: { kind: 'fixed', mm: 10 },
          align: 'center',
          headerStyle: { font: { size: 9, weight: 'bold', color: '#ffffff' }, background: '#1e40af', align: 'center' },
          cellStyle: { font: { size: 9 }, align: 'center' },
        },
        {
          id: 'col_image',
          header: 'Item',
          expression: 'row.mediaUrl',
          cellType: 'image',
          imageHeightMm: 10,
          width: { kind: 'fixed', mm: 14 },
          align: 'center',
          headerStyle: { font: { size: 9, weight: 'bold', color: '#ffffff' }, background: '#1e40af', align: 'center' },
          cellStyle: { align: 'center' },
        },
        {
          id: 'col_desc',
          header: 'Description',
          // Receipt-style: parent name first, then indented subItems with
          // their own options inline, then any top-level options for the
          // parent. `each:'<tpl>'` evaluates the template per subItem with
          // `row` rebound to each element, so the inner placeholders use
          // `row.productName` / `row.options` just like the outer scope.
          // Empty arrays collapse via the ternaries so plain lines stay
          // single-line.
          expression:
            "{{row.productName}}" +
            "{{row.subItems.length ? '\\n  • ' + (row.subItems | each:\"{{row.productName}}{{row.options.length ? ' (' + (row.options | pluck:optionName | join:', ') + ')' : ''}}\" | join:'\\n  • ') : ''}}" +
            "{{row.options.length ? '\\n  (' + (row.options | pluck:optionName | join:', ') + ')' : ''}}",
          width: { kind: 'fraction', fr: 3 },
          headerStyle: { font: { size: 9, weight: 'bold', color: '#ffffff' }, background: '#1e40af' },
          cellStyle: { font: { size: 9 } },
        },
        {
          id: 'col_qty',
          header: 'Qty',
          expression: 'row.qty',
          width: { kind: 'fixed', mm: 18 },
          align: 'right',
          headerStyle: { font: { size: 9, weight: 'bold', color: '#ffffff' }, background: '#1e40af', align: 'right' },
          cellStyle: { font: { size: 9 }, align: 'right' },
          footer: { kind: 'sum', format: 'number' },
        },
        {
          id: 'col_price',
          header: 'Price',
          expression: "row.price | currency:BHD",
          width: { kind: 'fixed', mm: 28 },
          align: 'right',
          headerStyle: { font: { size: 9, weight: 'bold', color: '#ffffff' }, background: '#1e40af', align: 'right' },
          cellStyle: { font: { size: 9 }, align: 'right' },
        },
        {
          id: 'col_total',
          header: 'Total',
          expression: 'row.total | currency:BHD',
          width: { kind: 'fixed', mm: 30 },
          align: 'right',
          headerStyle: { font: { size: 9, weight: 'bold', color: '#ffffff' }, background: '#1e40af', align: 'right' },
          cellStyle: { font: { size: 9, weight: 'bold' }, align: 'right' },
          footer: { kind: 'custom', expression: 'subTotal', format: 'currency:BHD' },
        },
      ],
    },
    {
      id: makeBlockId(),
      type: 'totals',
      position: { x: 110, y: 130 },
      size: { width: 85, height: 30 },
      labelWidth: 45,
      rows: [
        { label: 'Subtotal', expression: 'itemSubTotal', format: 'currency:BHD' },
        { label: 'VAT', expression: 'invoiceTaxTotal', format: 'currency:BHD' },
        { label: 'Discount', expression: 'itemDiscountTotal', format: 'currency:BHD' },
        { label: 'TOTAL', expression: 'total', format: 'currency:BHD', bold: true },
      ],
      style: { font: { size: 9 }, border: { top: { width: 0.5, color: '#cbd5e1', style: 'solid' }, bottom: { width: 0.5, color: '#cbd5e1', style: 'solid' }, left: { width: 0.5, color: '#cbd5e1', style: 'solid' }, right: { width: 0.5, color: '#cbd5e1', style: 'solid' } } },
    },
    {
      id: makeBlockId(),
      type: 'rich-text',
      position: { x: 15, y: 130 },
      size: { width: 85, height: 25 },
      html: '<b>Notes:</b><br>Payment due within 30 days.<br><i>Thank you for your business.</i>',
      style: { font: { size: 8, color: '#475569' } },
    },
    // Payments table — bound to top-level `invoicePayments[]`.
    {
      id: makeBlockId(),
      type: 'payments',
      position: { x: 110, y: 162 },
      size: { width: 84.5, height: 20, autoHeight: true },
      dataSource: 'invoicePayments',
      showHeader: false,
      zebra: false,
      zebraColor: '#fafafa',
      rowMinHeight: 7,
      currency: 'BHD',
      style: { font: { size: 8, weight: 'bold', color: '#0f172a' }, align: 'right', border: { top: { width: 0, color: '#e2e8f0', style: 'solid' }, bottom: { width: 0, color: '#e2e8f0', style: 'solid' }, left: { width: 0, color: '#e2e8f0', style: 'solid' }, right: { width: 0, color: '#e2e8f0', style: 'solid' }, } },

    },
    {
      id: makeBlockId(),
      type: 'qr-code',
      position: { x: 15, y: 190 },
      size: { width: 25, height: 25 },
      value: '{{invoiceNumber}}',
      ecLevel: 'M',
    },
    {
      id: makeBlockId(),
      type: 'signature',
      position: { x: 130, y: 190 },
      size: { width: 65, height: 20 },
      label: 'Authorized Signature',
    },
  ];

  const footerBlocks: Block[] = [
    {
      id: makeBlockId(),
      type: 'divider',
      position: { x: 15, y: 0 },
      size: { width: 180, height: 0.5 },
      thickness: 0.3,
      color: '#e2e8f0',
    },
    {
      id: makeBlockId(),
      type: 'text',
      position: { x: 15, y: 3 },
      size: { width: 100, height: 5 },
      text: '{{branchName}} | {{branchPhone}}',
      style: { font: { size: 7, color: '#94a3b8' } },
    },
    {
      id: makeBlockId(),
      type: 'page-number',
      position: { x: 125, y: 3 },
      size: { width: 70, height: 5 },
      format: 'Page {{page.current}} of {{page.total}}',
      style: { font: { size: 7, color: '#94a3b8' }, align: 'right' },
    },
  ];

  return {
    id: makeTemplateId(),
    tenantId: 'tenant_demo',
    name: 'Standard Tax Invoice — BHD',
    description: 'Invoice template bound to the Invo POS invoice payload (branch + lines + totals).',
    version: 1,
    createdAt: now,
    updatedAt: now,
    page: {
      size: 'A4',
      orientation: 'portrait',
      margins: { top: 0, right: 0, bottom: 0, left: 0 },
      background: '#ffffff',
    },
    direction: 'ltr',
    locale: 'en-BH',
    language: 'en',
    theme: {
      id: 'tenant_demo_theme',
      primaryColor: '#1e40af',
      onPrimaryColor: '#ffffff',
      accentColor: '#0ea5e9',
      textColor: '#0f172a',
      mutedColor: '#64748b',
      surfaceColor: '#f8fafc',
      fontFamily: '"Inter", "Helvetica Neue", Arial, sans-serif',
      arabicFontFamily: '"Noto Naskh Arabic", "Cairo", "Tajawal", Arial, sans-serif',
    },
    defaultStyle: {
      font: { family: '"Inter", Arial, sans-serif', size: 10, color: '#0f172a' },
    },
    sections: [
      { id: makeSectionId(), type: 'page-header', height: 32, blocks: headerBlocks },
      { id: makeSectionId(), type: 'body', blocks: bodyBlocks },
      { id: makeSectionId(), type: 'page-footer', height: 10, blocks: footerBlocks },
    ],
    sampleData: sampleInvoiceData(),
  };
}

/**
 * Verbatim Invo POS invoice payload — used as the sample binding source for
 * the designer preview and for PDF/HTML export when no `data` override is
 * provided. Mirrors the production shape exactly (including `refrenceNumber`
 * typo) so template authors see the real field names they'll bind against.
 *
 * Lines cover the common shapes a real receipt has:
 *   - Package items with `subItems[]` (Shawarma Meal, Falafel Wrap)
 *   - Plain items with `options[]` (Daal, Mango Lassi)
 *   - Bare items (Karak Tea, French Fries)
 *
 * subItems are line entries nested under a parent line (combo / package
 * contents). The Description column expression in the sample template
 * unfolds them as indented bullets so the template renders as a receipt
 * out of the box.
 */
export function sampleInvoiceData(): Record<string, unknown> {
  // Inline SVG product tile — distinct color per line so image rendering
  // in the items table is visually verifiable without external assets.
  const tile = (bg: string, label: string) =>
    'data:image/svg+xml;utf8,' +
    encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60">' +
      `<rect width="60" height="60" rx="6" fill="${bg}"/>` +
      `<text x="30" y="36" text-anchor="middle" fill="white" font-family="Arial" font-size="14" font-weight="700">${label}</text>` +
      '</svg>',
    );
  return {
    id: '69b8342c-a184-46ac-9728-b6d452f4d67b',
    branchId: '679cdb62-8807-427d-8bea-9916e726466e',
    refrenceNumber: '4',
    note: '',
    guests: 1,
    customerSignature: null,
    pointsDiscount: null,
    promoCoupon: null,
    couponId: null,
    chargeAmount: 0,
    chargePercentage: false,
    chargeTotal: 0,
    deliveryCharge: 0,
    discountAmount: 0,
    discountPercentage: false,
    discountTotal: 0,
    estimateSource: '',
    source: 'POS',
    customerContact: '',
    customerAddress: null,
    customerLatLang: '{}',
    status: 'Open',
    subTotal: 14.78,
    total: 14.78,
    paidAmount: 0,
    balance: 14.78,
    refunded: 0,
    appliedCredit: 0,
    customer: {
      companyId: '',
      companyGroup: '',
      contactName: '',
      creditLimit: null,
      type: 'Individual',
      saluation: '',
      name: '',
      phone: '',
      mobile: '',
      email: '',
      addresses: [],
      MSR: '',
      createdAt: null,
      notes: [],
      industry: null,
      parentName: '',
      hasChild: false,
      discountAmount: 0,
      vatNumber: '',
      openingBalance: [],
      updatedAt: '2026-05-12T14:19:35.128Z',
      oneSignalSegment: '',
      customerCredit: 0,
      availableCredit: 0,
      outStandingReceivable: 0,
      accountReceivable: 0,
      options: { allowHouseAccount: true },
      customFields: [],
      id: null,
      parentId: null,
      priceLabelId: null,
      currencyId: null,
      paymentTerm: 'custome',
      birthDay: null,
    },
    employee: null,
    driver: null,
    service: null,
    lines: [
      // ── Line 1: Package (Shawarma Meal) with three subItems — exactly
      // the payload the user provided.
      {
        id: '124bc85a-015e-47e7-b165-d177687151ba',
        invoiceId: '',
        branchId: '',
        note: null,
        accountId: '91f7b523-cd0c-480d-960d-bd4be0e30ff5',
        companyId: '',
        seatNumber: 0,
        qty: 1,
        price: 6.5,
        total: 6.5,
        subTotal: 6.5,
        defaultPrice: 0,
        translation: null,
        subItems: [
          {
            id: '4a3657ed-7ef9-49da-8ef9-5095a01f4a31',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc', name: 'الالو', type: 'menuItem', barcode: '3501368456906' },
            productName: 'الالو',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '569b737b-a238-4f31-ad6c-bfae014a6126',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [
              {
                id: 'f2842074-2616-46a1-b727-3d98ff0be3e4',
                optionName: 'Beef',
                optionGroupName: 'Meat Type',
                price: 0, qty: 0.5,
              },
            ],
            selectedItem: { id: '254f3eda-6b26-4e5c-9092-5e5aecabf245', name: 'Shawarmaa', type: 'menuItem', barcode: '1870941872658' },
            productName: 'Shawarmaa',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: '254f3eda-6b26-4e5c-9092-5e5aecabf245',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '910cf627-d53c-4023-bac9-a5f03159d8e6',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'a784a514-5557-4e64-a620-35d24c063583', name: 'Soft Drink', type: 'inventory', barcode: '7646476708304' },
            productName: 'Soft Drink',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'a784a514-5557-4e64-a620-35d24c063583',
            UOM: 'Pcs',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
        ],
        product: {},
        voidedItems: [],
        returnItems: [],
        createdAt: '2026-05-12 14:19:28.267',
        taxTotal: 0.5909090909090909,
        taxes: null,
        taxType: '',
        taxPercentage: 10,
        isInclusiveTax: true,
        discountAmount: 0,
        discountPercentage: false,
        discountTotal: 0,
        options: [],
        status: '',
        selectedItem: {
          id: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
          name: 'Shawarma Meal',
          type: 'package',
          barcode: '9159349354679',
        },
        productName: 'Shawarma Meal',
        productId: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
        taxName: 'VAT 10%',
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        accountName: 'Sales',
        UOM: null,
        weight: 0,
        weightUOM: 'KG',
        index: 0,
        parentId: null,
        mediaUrl: tile('#dc2626', 'SHW'),
      },
      // ── Line 2: Plain item with a single option.
      {
        id: 'a4b5c6d7-1111-2222-3333-444455556666',
        qty: 1,
        price: 1.45,
        total: 1.45,
        subTotal: 1.45,
        subItems: [],
        options: [
          {
            id: 'opt-daal-1',
            optionName: 'Small dall',
            optionGroupName: 'Daal Size',
            price: 1.45,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-daal', name: 'Daal', type: 'menuItem', barcode: '205' },
        productName: 'Daal',
        productId: 'p-daal',
        taxName: 'VAT 10%',
        taxTotal: 0.13,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 1,
        parentId: null,
        mediaUrl: "https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg",
      },
      // ── Line 3: Combo with multiple subItems (no options).
      {
        id: 'b7c8d9e0-2222-3333-4444-555566667777',
        qty: 1,
        price: 3.5,
        total: 3.5,
        subTotal: 3.5,
        subItems: [
          { id: 's1', qty: 1, price: 0, total: 0, productName: 'Pita Bread', selectedItem: { name: 'Pita Bread', type: 'menuItem' }, options: [] },
          { id: 's2', qty: 4, price: 0, total: 0, productName: 'Falafel Balls', selectedItem: { name: 'Falafel Balls', type: 'menuItem' }, options: [] },
          { id: 's3', qty: 1, price: 0, total: 0, productName: 'Tahini Sauce', selectedItem: { name: 'Tahini Sauce', type: 'menuItem' }, options: [] },
          { id: 's4', qty: 1, price: 0, total: 0, productName: 'Pickles', selectedItem: { name: 'Pickles', type: 'menuItem' }, options: [] },
        ],
        options: [],
        selectedItem: { id: 'p-falafel', name: 'Falafel Wrap', type: 'package', barcode: '301' },
        productName: 'Falafel Wrap',
        productId: 'p-falafel',
        taxName: 'VAT 10%',
        taxTotal: 0.32,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 2,
        parentId: null,
        mediaUrl: tile('#16a34a', 'FAL'),
      },
      // ── Line 4: Plain inventory item, no subItems, no options.
      {
        id: 'c9d0e1f2-3333-4444-5555-666677778888',
        qty: 1,
        price: 0.33,
        total: 0.33,
        subTotal: 0.33,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-karak', name: 'Karak Tea', type: 'menuItem', barcode: '501' },
        productName: 'Karak Tea',
        productId: 'p-karak',
        taxName: 'VAT 10%',
        taxTotal: 0.03,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 3,
        parentId: null,
        mediaUrl: tile('#7c3aed', 'KRK'),
      },
      // ── Line 5: Item with an option (size/sweetness).
      {
        id: 'd1e2f3a4-4444-5555-6666-777788889999',
        qty: 1,
        price: 1.75,
        total: 1.75,
        subTotal: 1.75,
        subItems: [],
        options: [
          {
            id: 'opt-lassi-1',
            optionName: 'Medium',
            optionGroupName: 'Sweetness',
            price: 0,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-lassi', name: 'Mango Lassi', type: 'menuItem', barcode: '602' },
        productName: 'Mango Lassi',
        productId: 'p-lassi',
        taxName: 'VAT 10%',
        taxTotal: 0.16,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 4,
        parentId: null,
        mediaUrl: tile('#0ea5e9', 'LSI'),
      },
      // ── Line 6: Plain side, qty > 1.
      {
        id: 'e3f4a5b6-5555-6666-7777-888899990000',
        qty: 2,
        price: 1.25,
        total: 1.25,
        subTotal: 1.25,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-fries', name: 'French Fries', type: 'menuItem', barcode: '701' },
        productName: 'French Fries',
        productId: 'p-fries',
        taxName: 'VAT 10%',
        taxTotal: 0.11,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 5,
        parentId: null,
        mediaUrl: tile('#eab308', 'FRY'),
      },
      // ── Line 1: Package (Shawarma Meal) with three subItems — exactly
      // the payload the user provided.
      {
        id: '124bc85a-015e-47e7-b165-d177687151ba',
        invoiceId: '',
        branchId: '',
        note: null,
        accountId: '91f7b523-cd0c-480d-960d-bd4be0e30ff5',
        companyId: '',
        seatNumber: 0,
        qty: 1,
        price: 6.5,
        total: 6.5,
        subTotal: 6.5,
        defaultPrice: 0,
        translation: null,
        subItems: [
          {
            id: '4a3657ed-7ef9-49da-8ef9-5095a01f4a31',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc', name: 'الالو', type: 'menuItem', barcode: '3501368456906' },
            productName: 'الالو',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '569b737b-a238-4f31-ad6c-bfae014a6126',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [
              {
                id: 'f2842074-2616-46a1-b727-3d98ff0be3e4',
                optionName: 'Beef',
                optionGroupName: 'Meat Type',
                price: 0, qty: 0.5,
              },
            ],
            selectedItem: { id: '254f3eda-6b26-4e5c-9092-5e5aecabf245', name: 'Shawarmaa', type: 'menuItem', barcode: '1870941872658' },
            productName: 'Shawarmaa',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: '254f3eda-6b26-4e5c-9092-5e5aecabf245',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '910cf627-d53c-4023-bac9-a5f03159d8e6',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'a784a514-5557-4e64-a620-35d24c063583', name: 'Soft Drink', type: 'inventory', barcode: '7646476708304' },
            productName: 'Soft Drink',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'a784a514-5557-4e64-a620-35d24c063583',
            UOM: 'Pcs',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
        ],
        product: {},
        voidedItems: [],
        returnItems: [],
        createdAt: '2026-05-12 14:19:28.267',
        taxTotal: 0.5909090909090909,
        taxes: null,
        taxType: '',
        taxPercentage: 10,
        isInclusiveTax: true,
        discountAmount: 0,
        discountPercentage: false,
        discountTotal: 0,
        options: [],
        status: '',
        selectedItem: {
          id: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
          name: 'Shawarma Meal',
          type: 'package',
          barcode: '9159349354679',
        },
        productName: 'Shawarma Meal',
        productId: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
        taxName: 'VAT 10%',
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        accountName: 'Sales',
        UOM: null,
        weight: 0,
        weightUOM: 'KG',
        index: 0,
        parentId: null,
        mediaUrl: tile('#dc2626', 'SHW'),
      },
      // ── Line 2: Plain item with a single option.
      {
        id: 'a4b5c6d7-1111-2222-3333-444455556666',
        qty: 1,
        price: 1.45,
        total: 1.45,
        subTotal: 1.45,
        subItems: [],
        options: [
          {
            id: 'opt-daal-1',
            optionName: 'Small dall',
            optionGroupName: 'Daal Size',
            price: 1.45,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-daal', name: 'Daal', type: 'menuItem', barcode: '205' },
        productName: 'Daal',
        productId: 'p-daal',
        taxName: 'VAT 10%',
        taxTotal: 0.13,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 1,
        parentId: null,
        mediaUrl: "https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg",
      },
      // ── Line 3: Combo with multiple subItems (no options).
      {
        id: 'b7c8d9e0-2222-3333-4444-555566667777',
        qty: 1,
        price: 3.5,
        total: 3.5,
        subTotal: 3.5,
        subItems: [
          { id: 's1', qty: 1, price: 0, total: 0, productName: 'Pita Bread', selectedItem: { name: 'Pita Bread', type: 'menuItem' }, options: [] },
          { id: 's2', qty: 4, price: 0, total: 0, productName: 'Falafel Balls', selectedItem: { name: 'Falafel Balls', type: 'menuItem' }, options: [] },
          { id: 's3', qty: 1, price: 0, total: 0, productName: 'Tahini Sauce', selectedItem: { name: 'Tahini Sauce', type: 'menuItem' }, options: [] },
          { id: 's4', qty: 1, price: 0, total: 0, productName: 'Pickles', selectedItem: { name: 'Pickles', type: 'menuItem' }, options: [] },
        ],
        options: [],
        selectedItem: { id: 'p-falafel', name: 'Falafel Wrap', type: 'package', barcode: '301' },
        productName: 'Falafel Wrap',
        productId: 'p-falafel',
        taxName: 'VAT 10%',
        taxTotal: 0.32,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 2,
        parentId: null,
        mediaUrl: tile('#16a34a', 'FAL'),
      },
      // ── Line 4: Plain inventory item, no subItems, no options.
      {
        id: 'c9d0e1f2-3333-4444-5555-666677778888',
        qty: 1,
        price: 0.33,
        total: 0.33,
        subTotal: 0.33,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-karak', name: 'Karak Tea', type: 'menuItem', barcode: '501' },
        productName: 'Karak Tea',
        productId: 'p-karak',
        taxName: 'VAT 10%',
        taxTotal: 0.03,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 3,
        parentId: null,
        mediaUrl: tile('#7c3aed', 'KRK'),
      },
      // ── Line 5: Item with an option (size/sweetness).
      {
        id: 'd1e2f3a4-4444-5555-6666-777788889999',
        qty: 1,
        price: 1.75,
        total: 1.75,
        subTotal: 1.75,
        subItems: [],
        options: [
          {
            id: 'opt-lassi-1',
            optionName: 'Medium',
            optionGroupName: 'Sweetness',
            price: 0,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-lassi', name: 'Mango Lassi', type: 'menuItem', barcode: '602' },
        productName: 'Mango Lassi',
        productId: 'p-lassi',
        taxName: 'VAT 10%',
        taxTotal: 0.16,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 4,
        parentId: null,
        mediaUrl: tile('#0ea5e9', 'LSI'),
      },
      // ── Line 6: Plain side, qty > 1.
      {
        id: 'e3f4a5b6-5555-6666-7777-888899990000',
        qty: 2,
        price: 1.25,
        total: 1.25,
        subTotal: 1.25,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-fries', name: 'French Fries', type: 'menuItem', barcode: '701' },
        productName: 'French Fries',
        productId: 'p-fries',
        taxName: 'VAT 10%',
        taxTotal: 0.11,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 5,
        parentId: null,
        mediaUrl: tile('#eab308', 'FRY'),
      },
      // ── Line 1: Package (Shawarma Meal) with three subItems — exactly
      // the payload the user provided.
      {
        id: '124bc85a-015e-47e7-b165-d177687151ba',
        invoiceId: '',
        branchId: '',
        note: null,
        accountId: '91f7b523-cd0c-480d-960d-bd4be0e30ff5',
        companyId: '',
        seatNumber: 0,
        qty: 1,
        price: 6.5,
        total: 6.5,
        subTotal: 6.5,
        defaultPrice: 0,
        translation: null,
        subItems: [
          {
            id: '4a3657ed-7ef9-49da-8ef9-5095a01f4a31',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc', name: 'الالو', type: 'menuItem', barcode: '3501368456906' },
            productName: 'الالو',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '569b737b-a238-4f31-ad6c-bfae014a6126',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [
              {
                id: 'f2842074-2616-46a1-b727-3d98ff0be3e4',
                optionName: 'Beef',
                optionGroupName: 'Meat Type',
                price: 0, qty: 0.5,
              },
            ],
            selectedItem: { id: '254f3eda-6b26-4e5c-9092-5e5aecabf245', name: 'Shawarmaa', type: 'menuItem', barcode: '1870941872658' },
            productName: 'Shawarmaa',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: '254f3eda-6b26-4e5c-9092-5e5aecabf245',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '910cf627-d53c-4023-bac9-a5f03159d8e6',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'a784a514-5557-4e64-a620-35d24c063583', name: 'Soft Drink', type: 'inventory', barcode: '7646476708304' },
            productName: 'Soft Drink',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'a784a514-5557-4e64-a620-35d24c063583',
            UOM: 'Pcs',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
        ],
        product: {},
        voidedItems: [],
        returnItems: [],
        createdAt: '2026-05-12 14:19:28.267',
        taxTotal: 0.5909090909090909,
        taxes: null,
        taxType: '',
        taxPercentage: 10,
        isInclusiveTax: true,
        discountAmount: 0,
        discountPercentage: false,
        discountTotal: 0,
        options: [],
        status: '',
        selectedItem: {
          id: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
          name: 'Shawarma Meal',
          type: 'package',
          barcode: '9159349354679',
        },
        productName: 'Shawarma Meal',
        productId: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
        taxName: 'VAT 10%',
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        accountName: 'Sales',
        UOM: null,
        weight: 0,
        weightUOM: 'KG',
        index: 0,
        parentId: null,
        mediaUrl: tile('#dc2626', 'SHW'),
      },
      // ── Line 2: Plain item with a single option.
      {
        id: 'a4b5c6d7-1111-2222-3333-444455556666',
        qty: 1,
        price: 1.45,
        total: 1.45,
        subTotal: 1.45,
        subItems: [],
        options: [
          {
            id: 'opt-daal-1',
            optionName: 'Small dall',
            optionGroupName: 'Daal Size',
            price: 1.45,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-daal', name: 'Daal', type: 'menuItem', barcode: '205' },
        productName: 'Daal',
        productId: 'p-daal',
        taxName: 'VAT 10%',
        taxTotal: 0.13,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 1,
        parentId: null,
        mediaUrl: "https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg",
      },
      // ── Line 3: Combo with multiple subItems (no options).
      {
        id: 'b7c8d9e0-2222-3333-4444-555566667777',
        qty: 1,
        price: 3.5,
        total: 3.5,
        subTotal: 3.5,
        subItems: [
          { id: 's1', qty: 1, price: 0, total: 0, productName: 'Pita Bread', selectedItem: { name: 'Pita Bread', type: 'menuItem' }, options: [] },
          { id: 's2', qty: 4, price: 0, total: 0, productName: 'Falafel Balls', selectedItem: { name: 'Falafel Balls', type: 'menuItem' }, options: [] },
          { id: 's3', qty: 1, price: 0, total: 0, productName: 'Tahini Sauce', selectedItem: { name: 'Tahini Sauce', type: 'menuItem' }, options: [] },
          { id: 's4', qty: 1, price: 0, total: 0, productName: 'Pickles', selectedItem: { name: 'Pickles', type: 'menuItem' }, options: [] },
        ],
        options: [],
        selectedItem: { id: 'p-falafel', name: 'Falafel Wrap', type: 'package', barcode: '301' },
        productName: 'Falafel Wrap',
        productId: 'p-falafel',
        taxName: 'VAT 10%',
        taxTotal: 0.32,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 2,
        parentId: null,
        mediaUrl: tile('#16a34a', 'FAL'),
      },
      // ── Line 4: Plain inventory item, no subItems, no options.
      {
        id: 'c9d0e1f2-3333-4444-5555-666677778888',
        qty: 1,
        price: 0.33,
        total: 0.33,
        subTotal: 0.33,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-karak', name: 'Karak Tea', type: 'menuItem', barcode: '501' },
        productName: 'Karak Tea',
        productId: 'p-karak',
        taxName: 'VAT 10%',
        taxTotal: 0.03,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 3,
        parentId: null,
        mediaUrl: tile('#7c3aed', 'KRK'),
      },
      // ── Line 5: Item with an option (size/sweetness).
      {
        id: 'd1e2f3a4-4444-5555-6666-777788889999',
        qty: 1,
        price: 1.75,
        total: 1.75,
        subTotal: 1.75,
        subItems: [],
        options: [
          {
            id: 'opt-lassi-1',
            optionName: 'Medium',
            optionGroupName: 'Sweetness',
            price: 0,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-lassi', name: 'Mango Lassi', type: 'menuItem', barcode: '602' },
        productName: 'Mango Lassi',
        productId: 'p-lassi',
        taxName: 'VAT 10%',
        taxTotal: 0.16,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 4,
        parentId: null,
        mediaUrl: tile('#0ea5e9', 'LSI'),
      },
      // ── Line 6: Plain side, qty > 1.
      {
        id: 'e3f4a5b6-5555-6666-7777-888899990000',
        qty: 2,
        price: 1.25,
        total: 1.25,
        subTotal: 1.25,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-fries', name: 'French Fries', type: 'menuItem', barcode: '701' },
        productName: 'French Fries',
        productId: 'p-fries',
        taxName: 'VAT 10%',
        taxTotal: 0.11,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 5,
        parentId: null,
        mediaUrl: tile('#eab308', 'FRY'),
      },
      // ── Line 1: Package (Shawarma Meal) with three subItems — exactly
      // the payload the user provided.
      {
        id: '124bc85a-015e-47e7-b165-d177687151ba',
        invoiceId: '',
        branchId: '',
        note: null,
        accountId: '91f7b523-cd0c-480d-960d-bd4be0e30ff5',
        companyId: '',
        seatNumber: 0,
        qty: 1,
        price: 6.5,
        total: 6.5,
        subTotal: 6.5,
        defaultPrice: 0,
        translation: null,
        subItems: [
          {
            id: '4a3657ed-7ef9-49da-8ef9-5095a01f4a31',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc', name: 'الالو', type: 'menuItem', barcode: '3501368456906' },
            productName: 'الالو',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '569b737b-a238-4f31-ad6c-bfae014a6126',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [
              {
                id: 'f2842074-2616-46a1-b727-3d98ff0be3e4',
                optionName: 'Beef',
                optionGroupName: 'Meat Type',
                price: 0, qty: 0.5,
              },
            ],
            selectedItem: { id: '254f3eda-6b26-4e5c-9092-5e5aecabf245', name: 'Shawarmaa', type: 'menuItem', barcode: '1870941872658' },
            productName: 'Shawarmaa',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: '254f3eda-6b26-4e5c-9092-5e5aecabf245',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '910cf627-d53c-4023-bac9-a5f03159d8e6',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'a784a514-5557-4e64-a620-35d24c063583', name: 'Soft Drink', type: 'inventory', barcode: '7646476708304' },
            productName: 'Soft Drink',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'a784a514-5557-4e64-a620-35d24c063583',
            UOM: 'Pcs',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
        ],
        product: {},
        voidedItems: [],
        returnItems: [],
        createdAt: '2026-05-12 14:19:28.267',
        taxTotal: 0.5909090909090909,
        taxes: null,
        taxType: '',
        taxPercentage: 10,
        isInclusiveTax: true,
        discountAmount: 0,
        discountPercentage: false,
        discountTotal: 0,
        options: [],
        status: '',
        selectedItem: {
          id: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
          name: 'Shawarma Meal',
          type: 'package',
          barcode: '9159349354679',
        },
        productName: 'Shawarma Meal',
        productId: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
        taxName: 'VAT 10%',
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        accountName: 'Sales',
        UOM: null,
        weight: 0,
        weightUOM: 'KG',
        index: 0,
        parentId: null,
        mediaUrl: tile('#dc2626', 'SHW'),
      },
      // ── Line 2: Plain item with a single option.
      {
        id: 'a4b5c6d7-1111-2222-3333-444455556666',
        qty: 1,
        price: 1.45,
        total: 1.45,
        subTotal: 1.45,
        subItems: [],
        options: [
          {
            id: 'opt-daal-1',
            optionName: 'Small dall',
            optionGroupName: 'Daal Size',
            price: 1.45,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-daal', name: 'Daal', type: 'menuItem', barcode: '205' },
        productName: 'Daal',
        productId: 'p-daal',
        taxName: 'VAT 10%',
        taxTotal: 0.13,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 1,
        parentId: null,
        mediaUrl: "https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg",
      },
      // ── Line 3: Combo with multiple subItems (no options).
      {
        id: 'b7c8d9e0-2222-3333-4444-555566667777',
        qty: 1,
        price: 3.5,
        total: 3.5,
        subTotal: 3.5,
        subItems: [
          { id: 's1', qty: 1, price: 0, total: 0, productName: 'Pita Bread', selectedItem: { name: 'Pita Bread', type: 'menuItem' }, options: [] },
          { id: 's2', qty: 4, price: 0, total: 0, productName: 'Falafel Balls', selectedItem: { name: 'Falafel Balls', type: 'menuItem' }, options: [] },
          { id: 's3', qty: 1, price: 0, total: 0, productName: 'Tahini Sauce', selectedItem: { name: 'Tahini Sauce', type: 'menuItem' }, options: [] },
          { id: 's4', qty: 1, price: 0, total: 0, productName: 'Pickles', selectedItem: { name: 'Pickles', type: 'menuItem' }, options: [] },
        ],
        options: [],
        selectedItem: { id: 'p-falafel', name: 'Falafel Wrap', type: 'package', barcode: '301' },
        productName: 'Falafel Wrap',
        productId: 'p-falafel',
        taxName: 'VAT 10%',
        taxTotal: 0.32,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 2,
        parentId: null,
        mediaUrl: tile('#16a34a', 'FAL'),
      },
      // ── Line 4: Plain inventory item, no subItems, no options.
      {
        id: 'c9d0e1f2-3333-4444-5555-666677778888',
        qty: 1,
        price: 0.33,
        total: 0.33,
        subTotal: 0.33,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-karak', name: 'Karak Tea', type: 'menuItem', barcode: '501' },
        productName: 'Karak Tea',
        productId: 'p-karak',
        taxName: 'VAT 10%',
        taxTotal: 0.03,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 3,
        parentId: null,
        mediaUrl: tile('#7c3aed', 'KRK'),
      },
      // ── Line 5: Item with an option (size/sweetness).
      {
        id: 'd1e2f3a4-4444-5555-6666-777788889999',
        qty: 1,
        price: 1.75,
        total: 1.75,
        subTotal: 1.75,
        subItems: [],
        options: [
          {
            id: 'opt-lassi-1',
            optionName: 'Medium',
            optionGroupName: 'Sweetness',
            price: 0,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-lassi', name: 'Mango Lassi', type: 'menuItem', barcode: '602' },
        productName: 'Mango Lassi',
        productId: 'p-lassi',
        taxName: 'VAT 10%',
        taxTotal: 0.16,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 4,
        parentId: null,
        mediaUrl: tile('#0ea5e9', 'LSI'),
      },
      // ── Line 6: Plain side, qty > 1.
      {
        id: 'e3f4a5b6-5555-6666-7777-888899990000',
        qty: 2,
        price: 1.25,
        total: 1.25,
        subTotal: 1.25,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-fries', name: 'French Fries', type: 'menuItem', barcode: '701' },
        productName: 'French Fries',
        productId: 'p-fries',
        taxName: 'VAT 10%',
        taxTotal: 0.11,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 5,
        parentId: null,
        mediaUrl: tile('#eab308', 'FRY'),
      },
      // ── Line 1: Package (Shawarma Meal) with three subItems — exactly
      // the payload the user provided.
      {
        id: '124bc85a-015e-47e7-b165-d177687151ba',
        invoiceId: '',
        branchId: '',
        note: null,
        accountId: '91f7b523-cd0c-480d-960d-bd4be0e30ff5',
        companyId: '',
        seatNumber: 0,
        qty: 1,
        price: 6.5,
        total: 6.5,
        subTotal: 6.5,
        defaultPrice: 0,
        translation: null,
        subItems: [
          {
            id: '4a3657ed-7ef9-49da-8ef9-5095a01f4a31',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc', name: 'الالو', type: 'menuItem', barcode: '3501368456906' },
            productName: 'الالو',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '569b737b-a238-4f31-ad6c-bfae014a6126',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [
              {
                id: 'f2842074-2616-46a1-b727-3d98ff0be3e4',
                optionName: 'Beef',
                optionGroupName: 'Meat Type',
                price: 0, qty: 0.5,
              },
            ],
            selectedItem: { id: '254f3eda-6b26-4e5c-9092-5e5aecabf245', name: 'Shawarmaa', type: 'menuItem', barcode: '1870941872658' },
            productName: 'Shawarmaa',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: '254f3eda-6b26-4e5c-9092-5e5aecabf245',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '910cf627-d53c-4023-bac9-a5f03159d8e6',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'a784a514-5557-4e64-a620-35d24c063583', name: 'Soft Drink', type: 'inventory', barcode: '7646476708304' },
            productName: 'Soft Drink',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'a784a514-5557-4e64-a620-35d24c063583',
            UOM: 'Pcs',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
        ],
        product: {},
        voidedItems: [],
        returnItems: [],
        createdAt: '2026-05-12 14:19:28.267',
        taxTotal: 0.5909090909090909,
        taxes: null,
        taxType: '',
        taxPercentage: 10,
        isInclusiveTax: true,
        discountAmount: 0,
        discountPercentage: false,
        discountTotal: 0,
        options: [],
        status: '',
        selectedItem: {
          id: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
          name: 'Shawarma Meal',
          type: 'package',
          barcode: '9159349354679',
        },
        productName: 'Shawarma Meal',
        productId: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
        taxName: 'VAT 10%',
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        accountName: 'Sales',
        UOM: null,
        weight: 0,
        weightUOM: 'KG',
        index: 0,
        parentId: null,
        mediaUrl: tile('#dc2626', 'SHW'),
      },
      // ── Line 2: Plain item with a single option.
      {
        id: 'a4b5c6d7-1111-2222-3333-444455556666',
        qty: 1,
        price: 1.45,
        total: 1.45,
        subTotal: 1.45,
        subItems: [],
        options: [
          {
            id: 'opt-daal-1',
            optionName: 'Small dall',
            optionGroupName: 'Daal Size',
            price: 1.45,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-daal', name: 'Daal', type: 'menuItem', barcode: '205' },
        productName: 'Daal',
        productId: 'p-daal',
        taxName: 'VAT 10%',
        taxTotal: 0.13,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 1,
        parentId: null,
        mediaUrl: "https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg",
      },
      // ── Line 3: Combo with multiple subItems (no options).
      {
        id: 'b7c8d9e0-2222-3333-4444-555566667777',
        qty: 1,
        price: 3.5,
        total: 3.5,
        subTotal: 3.5,
        subItems: [
          { id: 's1', qty: 1, price: 0, total: 0, productName: 'Pita Bread', selectedItem: { name: 'Pita Bread', type: 'menuItem' }, options: [] },
          { id: 's2', qty: 4, price: 0, total: 0, productName: 'Falafel Balls', selectedItem: { name: 'Falafel Balls', type: 'menuItem' }, options: [] },
          { id: 's3', qty: 1, price: 0, total: 0, productName: 'Tahini Sauce', selectedItem: { name: 'Tahini Sauce', type: 'menuItem' }, options: [] },
          { id: 's4', qty: 1, price: 0, total: 0, productName: 'Pickles', selectedItem: { name: 'Pickles', type: 'menuItem' }, options: [] },
        ],
        options: [],
        selectedItem: { id: 'p-falafel', name: 'Falafel Wrap', type: 'package', barcode: '301' },
        productName: 'Falafel Wrap',
        productId: 'p-falafel',
        taxName: 'VAT 10%',
        taxTotal: 0.32,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 2,
        parentId: null,
        mediaUrl: tile('#16a34a', 'FAL'),
      },
      // ── Line 4: Plain inventory item, no subItems, no options.
      {
        id: 'c9d0e1f2-3333-4444-5555-666677778888',
        qty: 1,
        price: 0.33,
        total: 0.33,
        subTotal: 0.33,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-karak', name: 'Karak Tea', type: 'menuItem', barcode: '501' },
        productName: 'Karak Tea',
        productId: 'p-karak',
        taxName: 'VAT 10%',
        taxTotal: 0.03,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 3,
        parentId: null,
        mediaUrl: tile('#7c3aed', 'KRK'),
      },
      // ── Line 5: Item with an option (size/sweetness).
      {
        id: 'd1e2f3a4-4444-5555-6666-777788889999',
        qty: 1,
        price: 1.75,
        total: 1.75,
        subTotal: 1.75,
        subItems: [],
        options: [
          {
            id: 'opt-lassi-1',
            optionName: 'Medium',
            optionGroupName: 'Sweetness',
            price: 0,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-lassi', name: 'Mango Lassi', type: 'menuItem', barcode: '602' },
        productName: 'Mango Lassi',
        productId: 'p-lassi',
        taxName: 'VAT 10%',
        taxTotal: 0.16,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 4,
        parentId: null,
        mediaUrl: tile('#0ea5e9', 'LSI'),
      },
      // ── Line 6: Plain side, qty > 1.
      {
        id: 'e3f4a5b6-5555-6666-7777-888899990000',
        qty: 2,
        price: 1.25,
        total: 1.25,
        subTotal: 1.25,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-fries', name: 'French Fries', type: 'menuItem', barcode: '701' },
        productName: 'French Fries',
        productId: 'p-fries',
        taxName: 'VAT 10%',
        taxTotal: 0.11,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 5,
        parentId: null,
        mediaUrl: tile('#eab308', 'FRY'),
      },
      // ── Line 1: Package (Shawarma Meal) with three subItems — exactly
      // the payload the user provided.
      {
        id: '124bc85a-015e-47e7-b165-d177687151ba',
        invoiceId: '',
        branchId: '',
        note: null,
        accountId: '91f7b523-cd0c-480d-960d-bd4be0e30ff5',
        companyId: '',
        seatNumber: 0,
        qty: 1,
        price: 6.5,
        total: 6.5,
        subTotal: 6.5,
        defaultPrice: 0,
        translation: null,
        subItems: [
          {
            id: '4a3657ed-7ef9-49da-8ef9-5095a01f4a31',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc', name: 'الالو', type: 'menuItem', barcode: '3501368456906' },
            productName: 'الالو',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'feb4dbd9-d442-4ac3-a1cb-a99c3ef1edbc',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '569b737b-a238-4f31-ad6c-bfae014a6126',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [
              {
                id: 'f2842074-2616-46a1-b727-3d98ff0be3e4',
                optionName: 'Beef',
                optionGroupName: 'Meat Type',
                price: 0, qty: 0.5,
              },
            ],
            selectedItem: { id: '254f3eda-6b26-4e5c-9092-5e5aecabf245', name: 'Shawarmaa', type: 'menuItem', barcode: '1870941872658' },
            productName: 'Shawarmaa',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: '254f3eda-6b26-4e5c-9092-5e5aecabf245',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
          {
            id: '910cf627-d53c-4023-bac9-a5f03159d8e6',
            qty: 1, price: 0, total: 0, subTotal: 0,
            options: [],
            selectedItem: { id: 'a784a514-5557-4e64-a620-35d24c063583', name: 'Soft Drink', type: 'inventory', barcode: '7646476708304' },
            productName: 'Soft Drink',
            parentId: '124bc85a-015e-47e7-b165-d177687151ba',
            productId: 'a784a514-5557-4e64-a620-35d24c063583',
            UOM: 'Pcs',
            isInclusiveTax: true,
            taxTotal: 0, taxPercentage: 0,
          },
        ],
        product: {},
        voidedItems: [],
        returnItems: [],
        createdAt: '2026-05-12 14:19:28.267',
        taxTotal: 0.5909090909090909,
        taxes: null,
        taxType: '',
        taxPercentage: 10,
        isInclusiveTax: true,
        discountAmount: 0,
        discountPercentage: false,
        discountTotal: 0,
        options: [],
        status: '',
        selectedItem: {
          id: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
          name: 'Shawarma Meal',
          type: 'package',
          barcode: '9159349354679',
        },
        productName: 'Shawarma Meal',
        productId: '92ef4a0d-e146-4b6f-b54b-c31ca824ae56',
        taxName: 'VAT 10%',
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        accountName: 'Sales',
        UOM: null,
        weight: 0,
        weightUOM: 'KG',
        index: 0,
        parentId: null,
        mediaUrl: tile('#dc2626', 'SHW'),
      },
      // ── Line 2: Plain item with a single option.
      {
        id: 'a4b5c6d7-1111-2222-3333-444455556666',
        qty: 1,
        price: 1.45,
        total: 1.45,
        subTotal: 1.45,
        subItems: [],
        options: [
          {
            id: 'opt-daal-1',
            optionName: 'Small dall',
            optionGroupName: 'Daal Size',
            price: 1.45,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-daal', name: 'Daal', type: 'menuItem', barcode: '205' },
        productName: 'Daal',
        productId: 'p-daal',
        taxName: 'VAT 10%',
        taxTotal: 0.13,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 1,
        parentId: null,
        mediaUrl: "https://cdn.pixabay.com/photo/2022/08/31/10/17/burger-7422970_1280.jpg",
      },
      // ── Line 3: Combo with multiple subItems (no options).
      {
        id: 'b7c8d9e0-2222-3333-4444-555566667777',
        qty: 1,
        price: 3.5,
        total: 3.5,
        subTotal: 3.5,
        subItems: [
          { id: 's1', qty: 1, price: 0, total: 0, productName: 'Pita Bread', selectedItem: { name: 'Pita Bread', type: 'menuItem' }, options: [] },
          { id: 's2', qty: 4, price: 0, total: 0, productName: 'Falafel Balls', selectedItem: { name: 'Falafel Balls', type: 'menuItem' }, options: [] },
          { id: 's3', qty: 1, price: 0, total: 0, productName: 'Tahini Sauce', selectedItem: { name: 'Tahini Sauce', type: 'menuItem' }, options: [] },
          { id: 's4', qty: 1, price: 0, total: 0, productName: 'Pickles', selectedItem: { name: 'Pickles', type: 'menuItem' }, options: [] },
        ],
        options: [],
        selectedItem: { id: 'p-falafel', name: 'Falafel Wrap', type: 'package', barcode: '301' },
        productName: 'Falafel Wrap',
        productId: 'p-falafel',
        taxName: 'VAT 10%',
        taxTotal: 0.32,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 2,
        parentId: null,
        mediaUrl: tile('#16a34a', 'FAL'),
      },
      // ── Line 4: Plain inventory item, no subItems, no options.
      {
        id: 'c9d0e1f2-3333-4444-5555-666677778888',
        qty: 1,
        price: 0.33,
        total: 0.33,
        subTotal: 0.33,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-karak', name: 'Karak Tea', type: 'menuItem', barcode: '501' },
        productName: 'Karak Tea',
        productId: 'p-karak',
        taxName: 'VAT 10%',
        taxTotal: 0.03,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 3,
        parentId: null,
        mediaUrl: tile('#7c3aed', 'KRK'),
      },
      // ── Line 5: Item with an option (size/sweetness).
      {
        id: 'd1e2f3a4-4444-5555-6666-777788889999',
        qty: 1,
        price: 1.75,
        total: 1.75,
        subTotal: 1.75,
        subItems: [],
        options: [
          {
            id: 'opt-lassi-1',
            optionName: 'Medium',
            optionGroupName: 'Sweetness',
            price: 0,
            qty: 1,
          },
        ],
        selectedItem: { id: 'p-lassi', name: 'Mango Lassi', type: 'menuItem', barcode: '602' },
        productName: 'Mango Lassi',
        productId: 'p-lassi',
        taxName: 'VAT 10%',
        taxTotal: 0.16,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 4,
        parentId: null,
        mediaUrl: tile('#0ea5e9', 'LSI'),
      },
      // ── Line 6: Plain side, qty > 1.
      {
        id: 'e3f4a5b6-5555-6666-7777-888899990000',
        qty: 2,
        price: 1.25,
        total: 1.25,
        subTotal: 1.25,
        subItems: [],
        options: [],
        selectedItem: { id: 'p-fries', name: 'French Fries', type: 'menuItem', barcode: '701' },
        productName: 'French Fries',
        productId: 'p-fries',
        taxName: 'VAT 10%',
        taxTotal: 0.11,
        taxPercentage: 10,
        isInclusiveTax: true,
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        discountAmount: 0,
        discountTotal: 0,
        accountName: 'Sales',
        index: 5,
        parentId: null,
        mediaUrl: tile('#eab308', 'FRY'),
      },
    ],
    invoicePayments: [],
    employeeName: 'Ahmed',
    branchName: 'demo',
    customerName: null,
    driverName: '',
    smallestCurrency: 0.025,
    roundingType: 'negative',
    roundingTotal: 0,
    invoiceDate: '2026-05-12',
    createdAt: '2026-05-12 14:19:28.238',
    updatedDate: '2026-05-12T14:19:35.128Z',
    isInclusiveTax: true,
    itemSubTotal: 14.78,
    invoiceTaxTotal: 1.34,
    houseAccount: false,
    onlineStatus: '',
    rejectReason: '',
    onlineData: { sessionId: '', onlineStatus: 'Accepted' },
    grubTechData: {},
    customerVatNumber: null,
    companyVatNumber: '311026522800005',
    currentInvoiceStatus: '',
    minimumOrder: 0,
    isPaid: false,
    mediaUrl: '',
    addressKey: '',
    attachment: null,
    logs: [],
    mergeWithInvoiceNumber: null,
    branchAddress: 'Bahrain',
    branchPhone: '33121221',
    branchCustomFields: [],
    customerEmail: null,
    salesEmployeeName: null,
    discountType: '',
    customerPhone: null,
    aggregator: '',
    aggregatorId: null,
    recurringInvoiceId: null,
    chargeType: '',
    taxesDetails: [
      {
        taxId: '5f35f5af-f18f-4067-9ef4-0b1b43c286f0',
        taxName: 'VAT 10%',
        total: 1.34,
        taxPercentage: 10,
      },
    ],
    itemDiscountTotal: 0,
    customFields: null,
    externalId: '',
    appliedCreditTotal: 0,
    creditNoteTotal: 0,
    paymentTotal: 0,
    refundTotal: 0,
    companyId: '',
    cartHash: null,
    countryCode: null,
    toPaidAmount: 0,
    freeDeliveryOver: null,
    tempDeliveryCharge: null,
    shippingOptions: null,
    oldTableId: null,
    deliveryNote: null,
    applePayTokendata: null,
    tableGroupName: null,
    unPaidAmount: 0,
    couponType: null,
    shopperId: null,
    oldReadyTime: null,
    subscriptionId: null,
    employeeId: 'cdbdd16b-a655-4703-bec6-c939acb975eb',
    chargesTaxDetails: null,
    terminalId: null,
    tableId: null,
    serviceId: '69ca0c0e-c117-49f4-9b47-4a7880bc2bf7',
    customerId: null,
    estimateId: null,
    printTime: null,
    readyTime: null,
    departureTime: null,
    arrivalTime: null,
    claimTime: null,
    discountId: null,
    chargeId: null,
    scheduleTime: null,
    mergeWith: null,
    driverId: null,
    onlineActionTime: null,
    writeOffDate: null,
    serviceName: 'Mcdonalds',
    tableName: null,
    invoiceNumber: 'T22-111',
    mediaId: null,
    salesEmployeeId: null,
    paymentTerm: null,
    dueDate: '2026-05-12T23:59:59.000Z',
    receivableAccountId: null,
    // Designer-only context. The real renderer overrides these per page.
    page: { current: 1, total: 1 },
  };
}
