#!/usr/bin/env node
/**
 * Bumps the patch number of the project's release version.
 *
 *   src/assets/version.json   ← source of truth
 *   src/version.ts            ← regenerated, imported by the SSR Logger
 *                               so the release tag baked into the
 *                               bundle matches the version users see.
 *
 * Runs on `npm run build` / `build:ssr` via prebuild hooks. Standalone:
 *   node scripts/bump-version.mjs
 *
 * Set major/minor by editing src/assets/version.json directly — this
 * script only touches the patch component.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const versionJsonPath = resolve(root, 'src/assets/version.json');
const versionTsPath = resolve(root, 'src/version.ts');

if (!existsSync(resolve(root, 'src/assets'))) {
  mkdirSync(resolve(root, 'src/assets'), { recursive: true });
}

if (!existsSync(versionJsonPath)) {
  writeFileSync(versionJsonPath, JSON.stringify({ version: 'v0.0.0' }, null, 2) + '\n');
}

const json = JSON.parse(readFileSync(versionJsonPath, 'utf8'));
const current = (json.version || '0.0.0').toString();

const match = current.match(/^(\D*)(\d+)\.(\d+)\.(\d+)(.*)$/);
if (!match) {
  console.error(
    `[bump-version] Could not parse version "${current}" in ${versionJsonPath} — expected something like "v1.4.9".`
  );
  process.exit(1);
}
const [, prefix, major, minor, patch, suffix] = match;

const ciBuild = process.env.CODEBUILD_BUILD_NUMBER;
const nextPatch = ciBuild && /^\d+$/.test(ciBuild)
  ? ciBuild
  : String(Number(patch) + 1);
const next = `${prefix}${major}.${minor}.${nextPatch}${suffix}`;
const source = ciBuild ? `CODEBUILD_BUILD_NUMBER=${ciBuild}` : 'local +1';

json.version = next;
writeFileSync(versionJsonPath, JSON.stringify(json, null, 2) + '\n');

writeFileSync(
  versionTsPath,
  `// AUTO-GENERATED by scripts/bump-version.mjs — do not edit by hand.\n` +
    `// To change major/minor, edit src/assets/version.json's "version" field;\n` +
    `// the patch is auto-bumped on every \`npm run build\` / \`build:ssr\`.\n` +
    `// Imported by:\n` +
    `//   - src/logger/index.ts                          (SSR Logger)\n` +
    `export const RELEASE = '${next}';\n`
);

console.log(`[bump-version] ${current} -> ${next} (${source})`);
