#!/usr/bin/env node
/**
 * Bumps the patch number of the project's release version.
 *
 *   src/assets/version.json   ← source of truth (also loaded at runtime by
 *                               appServices.loadAppVersion for app display)
 *   src/version.ts            ← regenerated, imported by both loggers so the
 *                               release tag baked into bundles matches the
 *                               version users see.
 *
 * Runs on `npm run build` and `npm run build:ssr` via the prebuild hooks in
 * package.json. Also runnable standalone: `node scripts/bump-version.mjs`.
 *
 * To set major/minor, edit src/assets/version.json directly — this script
 * only touches the patch component (and rewrites src/version.ts).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const versionJsonPath = resolve(root, 'src/assets/version.json');
const versionTsPath = resolve(root, 'src/version.ts');

const json = JSON.parse(readFileSync(versionJsonPath, 'utf8'));
const current = (json.version || '0.0.0').toString();

// Accept "v1.4.9", "1.4.9", "1.4.9-beta", etc. Bump only the numeric patch;
// preserve any prefix (e.g. "v") and any suffix (e.g. "-beta", "+sha.abc").
const match = current.match(/^(\D*)(\d+)\.(\d+)\.(\d+)(.*)$/);
if (!match) {
  console.error(
    `[bump-version] Could not parse version "${current}" in ${versionJsonPath} — expected something like "v1.4.9".`
  );
  process.exit(1);
}
const [, prefix, major, minor, patch, suffix] = match;

// In CI (AWS CodeBuild), use the project-wide monotonic build number as the
// patch so every deploy has a unique, traceable version — the build number
// in the logger maps 1:1 to the CodeBuild console.
// Locally, fall back to a simple +1 increment from the committed value.
const ciBuild = process.env.CODEBUILD_BUILD_NUMBER;
const nextPatch = ciBuild && /^\d+$/.test(ciBuild)
  ? ciBuild
  : String(Number(patch) + 1);
const next = `${prefix}${major}.${minor}.${nextPatch}${suffix}`;
const source = ciBuild ? `CODEBUILD_BUILD_NUMBER=${ciBuild}` : 'local +1';

json.version = next;
writeFileSync(versionJsonPath, JSON.stringify(json, null, 2) + '\n');

writeFileSync(
  versionTsPath,
  `// AUTO-GENERATED by scripts/bump-version.mjs — do not edit by hand.\n` +
    `// To change major/minor, edit src/assets/version.json's "version" field;\n` +
    `// the patch is auto-bumped on every \`npm run build\` / \`build:ssr\`.\n` +
    `// Imported by:\n` +
    `//   - src/logger/index.ts                          (SSR Logger)\n` +
    `//   - src/app/services/logger/logger.service.ts   (browser LoggerService)\n` +
    `export const RELEASE = '${next}';\n`
);

console.log(`[bump-version] ${current} -> ${next} (${source})`);
